### ISSUE TITLE
Each installation should create an own virtualhost file

### ISSUE THREAD

**Issue by lucasdavila** [ieducativa/ieducar-installer#1]
Probably it could use the name of the installation dir.

**Comment by aurelioribeiro21** [comment]
Olá Lucas estou tendo problema na aquisição do arquivo do bootstrap alguma luz ai?



  * baixando dump banco de dados

--2017-03-04 18:57:32--  https://dl.dropboxusercontent.com/u/7006796/cdn/ieducat            iva/ieducar/comunidade/bootstrap.backup.zip
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 45.58.74.37
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|45.58.74.37|            :443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-04 18:57:33 ERROR 404: Not Found.

unzip:  cannot find or open bootstrap.backup.zip, bootstrap.backup.zip.zip or bo            otstrap.backup.zip.ZIP.



  Desculpe, mas a instalação não pode continuar pois ocorreu algum erro inesperado.

  Por favor, tente novamente.

**Comment by lucasdavila** [comment]
Oi @aurelioribeiro21 

Este instalador foi descontinuado, já não atuo mais na comunidade do iEducar.

Recomendo que você acesse a comunidade do iEducar no portal do software público, e tente instalar por lá.

Qualquer dúvida, você pode usar o forum da comunidade no mesmo portal.

Abraço.
